version: '2'
services:
    nginx:
        build: ./docker/nginx/
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
        links:
            - php
    php:
        build: ./docker/php/
        volumes:
            - ./:/var/www